### PR TITLE
Adding support for more activity commands

### PR DESCRIPTION
**Pull request by paul90**
Moving the site flag to the end of the line

Adding support for:
* MINE
  * **yes** - includes origin site's pages in the activity list,
  * **no** - exclude origin site's pages from the activity list (useful for use with roster when you just want pages from the sites in the roster),
  * **only** - only include pages that have a twin on the origin server
  * **exclude** - exclude pages that have twin on the origin server

### CODE REVIEW

**Comment by paul90** [comment]
Still not sure of the best way to link in a conversation view, or the narrative chart; 8cd195d provides an initial suggestion.

**Comment by WardCunningham** [comment]
I find the flags positioned to the right to be pleasant, calm even, compared to the jumble we have had before. I'm thinking the rightmost flag should be the newest. Likewise, when opening a conversation, the newest should be on the right.

This seems to handle long lists of flags reasonably well. 

I wonder if the conversation link, ◊, should be associated with the flags, not the title. Clicking individual flags opens each one in turn, clicking the conversation link would just open all the flags at once. It is an operation on flags (and their specific sites) not the site-independent page name.

I recommend the right pointing triangle, ▶︎, serve the role of opening many flags.

There doesn't seem to be any need for opening a new tab when calling up a conversation. It would mean adding lots of pages but the browser back button should remove them just as easily (have to check that lib/state.coffee can work this way).

I'd like to see the Roster plugin have similar mass-opening behavior. This would solve the problem of how to fetch a bunch of sitemaps when viewing the roster.

I would be happy to work on some of these and add commits to your pull request.

**Comment by WardCunningham** [comment]
> There doesn't seem to be any need for opening a new tab when calling up a conversation.

My commit 3fddfa4 addresses this one observation by calling wiki.doInternalLink repeatedly. This seems to do the right thing in every case. I guess it races ahead of the browser history state update and consequently makes the back button work as desired by remove all of the pages added by a large version of this operation.

This command could finish up by offering one last page with the narrative chart thereby collapsing the two options into one ▶︎ button. The Conversation Summary page could be in this plugin's pages so that it would be reliably there but still could be overridden and customised if, say, the Narrative Chart plugin took options.

**Comment by WardCunningham** [comment]
> I'm thinking the rightmost flag should be the newest. Likewise, when opening a conversation, the newest should be on the right.

This was an easy change once I found the right invocation of sort. Given its placement in the code, I can't imagine that there could be much interaction with other features. The flags are ordered correctly and the conversation pages come up in that order. I haven't run the narrative chart so I don't know if there is an order dependency there.

**Comment by WardCunningham** [comment]
@paul90, thank you for continuing to push this work forward. I'm wondering what you think we need to drive this work to completion besides resolution on things already discussed here? 

* [ ] feature interaction testing, possibly "all pairs". [wikipedia](http://en.wikipedia.org/wiki/All-pairs_testing)
* [ ] unit testing of parsing logic at least, possibly as in #13.
* [ ] document commands in About page.
* [ ] new plugin pages, carefully titled, for most useful configurations.
* [ ] new plugin page with how-to documentation for community managers.
* [ ] corresponding improvements in Roster to make loading sitemaps easy.

I'm happy to write the about pages but would like to work from a draft list rather than reading the code. This list is around but now scattered.

I'd also like to get Mike Caulfield to think through the capabilities we've created and make sure they do solve the real problems he has experienced organizing communities. This is more than a quick read. He will need to experiment.

**Comment by paul90** [comment]
> I haven't run the narrative chart so I don't know if there is an order dependency there.

For the narrative chart the order of the flags has little effect. It changes the order that the twins are merged into the combined journal, and the vertical ordering of the sites.

**Comment by paul90** [comment]
Think that is a good list to be going on with - I think we discussed adding the ability to ignore certain pages.

I will merge rosters, #11, into this pull request - will make things slightly easier to work with. *Will probably merge the tests, #13, in as well.*

**Comment by paul90** [comment]
Reverting 336e4f4, so the flag data is still sorted newest to oldest - so that pages still get sorted correctly using the date of the first item in the flag data array. We change the rendering of the flags so that the newest is on the right.

**Comment by WardCunningham** [comment]
If we wanted to reverse the flag order we would need to make a corresponding changes to the subsequent sort.

https://github.com/fedwiki/wiki-plugin-activity/blob/336e4f48f2fcab0cb588465f2f71a9ea253c7b60/client/activity.coffee#L267

Here a[0] should be replaced with a[a.length-1] and similarly b[0] changed too.

I tried to add this fix but seem to have caught you in the midst of other work. I'm off to start my work day instead. But thanks for catching this important disfunction.

**Comment by paul90** [comment]
Commit 95c8edc adds the loading of sitemaps for the sites in a roster when using `ROSTER` command.

**Comment by paul90** [comment]
77c7e69 adds `Activity Test Pages` which provides a link into the generated test pages.

**Comment by WardCunningham** [comment]
These test pages are awesome.

**Comment by WardCunningham** [comment]
I wonder, should the Activity plugin render within a gray background?

When the plugin shares the page with other content, and especially content following the plugin, it can be hard to tell where results stop and other content begins. 

We mostly follow the practice of emitting text (from Paragraph, Markdown, Html and MathJax) onto a white background while more algorithmic outputs (from Method, Code and Grep) are bounded within a gray background.

A gray background will require some extra pad that will crowd long titles even more. There will always be long titles. A gray background will help keep them from confusing the rest of a page.

**Comment by paul90** [comment]
Move the links to open the conversation and narrative chart to the right margin. Also vertically align them if both links are present.
screen shot 2015-05-30 at 14 35 04

Also switched to using `»` to open the conversation, better than the original symbol...

**Comment by WardCunningham** [comment]
I love it.

**Comment by WardCunningham** [comment]
I've added a page describing configuration markup.

I'm thinking this pull request is about ready to go. Our checklist asks for more documentation but that will come with use in upcoming happenings.

The configuration markup about page depends on a recently merged Markdown extension which should be released before or together with these commits. https://github.com/fedwiki/wiki-plugin-markdown/pull/11

**Comment by WardCunningham** [comment]
Yikes. Travis CI build errors. Seems npm couldn't install grunt-contrib-coffee when running on iojs. This doesn't seem to be our problem and wouldn't be avoided by not merging. I recommend merge with caution.

**Comment by paul90** [comment]
Just re-ran the Travis CI tests, and all is well :smile:

**Comment by WardCunningham** [comment]
Let's do it.

**Comment by paul90** [comment]
Published as + wiki-plugin-activity@0.2.3

**Pull request merged**
