### PR TITLE
resolving some temporal spacing and maybe ordering

### PR DESCRIPTION
**Pull request by paul90**
The spacing between flags was not correct, moving it so it is not between flags for variants that have the same date.

Part of a fix for #23 ???

### CODE REVIEW

**Comment by paul90** [comment]
But, the flags are in the wrong order, should be newest on the right....

**Comment by WardCunningham** [comment]
I think our experience with 'conversation clubs' was that the newest flag should be on the right and that when opened, the lineup of twin pages should be similarly ordered with newest on the right.

The motivations was: if the last added is going to be selected, make it the one most likely to be wanted. Scrolling left to find earlier versions made sense then.

**Comment by paul90** [comment]
this looks a lot better - for some reason I hadn't spotted that the original version was adding flags at the start of the string while building up the display. Strange as that was a change I made earlier this year...

**Comment by WardCunningham** [comment]
Before
image

After
image

**Comment by paul90** [comment]
Published as + wiki-plugin-activity@0.2.7

**Pull request merged**
