### PR TITLE
virtual dom and improved merge

### PR DESCRIPTION
**Pull request by paul90**
Two significant changes in this branch.

1. Merge will merge the new site into the existing merged data, rather than doing a merge for the whole of the current neighbourhood.

2. We replace the current display with using virtual-dom, although the virtual-dom tree is created from scratch this is still faster as only the differences get applied to the browser dom.

Also see #19

### CODE REVIEW

**Comment by WardCunningham** [comment]
I've read but not tested these commits. If you're confident, let's merge.

This and "SINCE 4 weeks" will make large Rosters much more useful. Thanks for carrying the weight on this improvement.

**Comment by paul90** [comment]
For anybody who wants to test this new version, I have published a pre-release to npm. It can be installed using `npm install wiki-plugin-activity@0.2.5-pre.1`.

**Comment by WardCunningham** [comment]
I've installed the pre-release on asia.wiki.org and browsed all of the Recent Activity for the last week, 2000 pages total. Browsing was always smooth and quick while sitemaps loaded. I repeated the experiment watching with developer tools and saw a worst-case animation frame of 25 msec. Very acceptable. Awesome even. 

image

**Comment by paul90** [comment]
Published as + wiki-plugin-activity@0.2.5

**Pull request merged**
